### ISSUE TITLE
load_results() missing 1 required positional argument: 'model_or_file'

### ISSUE THREAD

**Issue by karenacollins** [kima-org/kima#16]
A newbie question. I am trying to run the 51 Peg example (on a windows 11 installation using Spyder). The code looks like this:

import kima
from kima import RVData, RVmodel
from kima.examples import _51Peg
model = _51Peg(run=True)
res = kima.load_results()
res.plot1()
res.plot2()

I get the following error,  and I'm not sure where the results file is located. What should be done to resolve this issue?

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\py3compat.py", line 356, in compat_exec
    exec(code, globals, locals)
  File "c:\users\karen\documents\python code\untitled0.py", line 15, in <module>
    res = kima.load_results()
TypeError: load_results() missing 1 required positional argument: 'model_or_file'

Thanks!
Karen

**Comment by j-faria** [comment]
Hello Karen,

Very valid question! The `load_results()` function has changed recently and now requires the model as an argument. So, in general,
```py
res = kima.load_results(model)
```
would work.

In this particular case, since the example runs in a specific directory (where the file `_51peg\__init__.py` is), the above still fails (and it shouldn't). I'm publishing a fix to pypi very soon, but in the meantime this should work for the examples:

```py
model, res = _51Peg(run=True, load=True)
```
